In [2]:
def add(a,b):
 return a+b

In [3]:
x=10
y=20
res = add(x,y)
print(res)

30


In [7]:
def welcome():
  print("welcome to python lab")
welcome()

welcome to python lab


In [8]:
def square(n):
  return n*n
print(square(10))

100


In [12]:
def student(name, age =21):
  print(name,age )
student("Rahul",25)

Rahul 25


In [13]:
def student(name,age):
  print(name,age)
student(age =20,name="Anshika")

Anshika 20


variable length arguments(*args)

In [15]:
def add(*nums):
  total=0
  for x in nums:
    total += x
  return (total)
res1 =add(10, 20)
print(res1)
res2 =add(1,20,30,40,50)
print(res2)


30
141


In [25]:
import numpy as np
n = int(input("How many numbers"))
numbers = []
for i in range(n):
  x = int(input("Enter a number"))
  numbers.append(x)

arr = np.array(numbers)
print("shape", arr.shape)
print("Dim",arr.ndim)
print("type",type(arr))
print("Array type",arr.dtype)

How many numbers4
Enter a number1
Enter a number2
Enter a number3
Enter a number4
shape (4,)
Dim 1
type <class 'numpy.ndarray'>
Array type int64


In [23]:
def create_Array(n):
  numbers = []
  for i in range(n):
    x = int(input("Enter a number"))
    numbers.append(x)
  return np.array(numbers)

n = int(input("How many numbers"))
arr = create_Array(n)
arr = np.array(numbers)
print("shape", arr.shape)
print("Dim",arr.ndim)
print("type",type(arr))
print("Array type",arr.dtype)

How many numbers4
Enter a number1
Enter a number2
Enter a number3
Enter a number4
shape (1,)
Dim 1
type <class 'numpy.ndarray'>
Array type int64


In [24]:
def cal(a,b):
  return a+b,a-b,a*b,a/b
add,sub,mul,div =cal(10,20)
print(add,sub,mul,div)

30 -10 200 0.5


In [26]:
np.square(arr)


array([ 1,  4,  9, 16])

Reshaping


In [28]:
data=np.arange(1,13)
a=data.reshape(3,4)
b=data.reshape(4,3)
c=data.reshape(2,-1)
print(f'1-D data \n{data}')
print(f'2-D data \n{a}')
print(f'2-D data \n{b}')
print(f'2-D data \n{c}')

1-D data 
[ 1  2  3  4  5  6  7  8  9 10 11 12]
2-D data 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
2-D data 
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
2-D data 
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


flatten() and ravel

In [30]:
data =np.array([[1,2,3],[4,5,6]])
print("orig data",data.ndim)
flat1 = data.flatten()
print("Flatten flat1",flat1)
flat2 = data.ravel()
print("ravel flat2",flat2)

orig data 2
Flatten flat1 [1 2 3 4 5 6]
ravel flat2 [1 2 3 4 5 6]


combining Arrays
 np.concatenate()
np.vstack()
np.hstack()


In [31]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.concatenate((a,b))
print("Concatenate \n",c)
print("vstack \n", np.vstack((a,b)))
print("Hstack \n", np.hstack((a,b)))

Concatenate 
 [1 2 3 4 5 6]
vstack 
 [[1 2 3]
 [4 5 6]]
Hstack 
 [1 2 3 4 5 6]


vectorization

In [32]:
data =np.array([10,20,30,40,50])
res =[]
for x in data:
  res.append(x*2)
  print(np.array(res))

[20]
[20 40]
[20 40 60]
[20 40 60 80]
[ 20  40  60  80 100]


In [33]:
ves_res =data*2
print(ves_res)

[ 20  40  60  80 100]


In [34]:
a = np.array([10,20,30])
b = np.array([1,2,3])
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[11 22 33]
[ 9 18 27]
[10 40 90]
[10. 10. 10.]


In [35]:
marks=np.array([35,45,52,68,78])
passed=marks >=40
between =marks[(marks>=50)&(marks<=80)]
print(f'Marks for marks >=40{passed}')
print(f'passing Marks:{marks[passed]}')
print(f'Marks between 50 and 80{between}')

Marks for marks >=40[False  True  True  True  True]
passing Marks:[45 52 68 78]
Marks between 50 and 80[52 68 78]


Broadcasting


In [36]:
arr =np.array([1,2,3])
res =arr+1
print(res)

[2 3 4]


In [38]:
a=np.array([2,4,6])
b=np.array([[1,2,3],[7,8,9]])
res= a+b
print(res)

[[ 3  6  9]
 [ 9 12 15]]


In [39]:
a = np.array([12,24,35,45,60,70])
b = np.array(["Adult","Minor"])
res = np.where(a>18, "Adult", "Minor")
print(res)

['Minor' 'Adult' 'Adult' 'Adult' 'Adult' 'Adult']
